# Generated by Django 5.0.2 on 2025-03-04 14:06

import django.core.files.storage
import django.utils.timezone
import posts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="postimage",
            options={"ordering": ["created_at"]},
        ),
        migrations.RemoveField(
            model_name="postimage",
            name="order",
        ),
        migrations.AddField(
            model_name="postimage",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="postimage",
            name="image",
            field=models.ImageField(
                storage=django.core.files.storage.FileSystemStorage(
                    base_url="/media/posts/",
                    location="/home/chekh/Desktop/task_4c/backend/media/posts",
                ),
                upload_to=posts.models.post_image_path,
            ),
        ),
    ]
