# Generated by Django 5.0.2 on 2025-03-04 14:06

import django.core.files.storage
import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="profile_photo",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=django.core.files.storage.FileSystemStorage(
                    base_url="/media/profiles/",
                    location="/home/chekh/Desktop/task_4c/backend/media/profiles",
                ),
                upload_to=users.models.user_profile_photo_path,
            ),
        ),
    ]
