# Generated by Django 5.0.2 on 2025-03-05 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_customuser_profile_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="delivery_address",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="phone",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
